// Pseudocode listings for the dual-pane player. Line numbers referenced by
// step builders (`step.line`) are 1-based indexes into these arrays.

export const ARRAY_PSEUDOCODE = {
  add: [
    'procedure arrayAdd(array, value)',
    '  n ← length(array)',
    '  array[n] ← value',
    '  length ← n + 1',
    'end procedure',
  ],
  insert: [
    'procedure arrayInsert(array, pos, value)',
    '  n ← length(array)',
    '  for i ← n downto pos + 1 do',
    '    array[i] ← array[i - 1]',
    '  array[pos] ← value',
    '  length ← n + 1',
    'end procedure',
  ],
  remove: [
    'procedure arrayRemove(array, pos)',
    '  locate index pos',
    '  removed ← array[pos]',
    '  for i ← pos to length(array) - 2 do',
    '    array[i] ← array[i + 1]',
    '  length ← length(array) - 1',
    '  return removed',
    'end procedure',
  ],
};

export const LINKED_LIST_PSEUDOCODE = {
  add: [
    'procedure listAdd(head, value)',
    '  node ← newNode(value)',
    '  if head = null then',
    '    head ← node',
    '  else',
    '    cur ← head',
    '    while cur.next ≠ null do cur ← cur.next',
    '    cur.next ← node',
    '  return head',
  ],
  insert: [
    'procedure listInsert(head, value, pos)',
    '  node ← newNode(value)',
    '  if pos = 0 then',
    '    node.next ← head',
    '    head ← node',
    '  else',
    '    cur ← head',
    '    advance cur to position pos - 1',
    '    node.next ← cur.next',
    '    cur.next ← node',
    '  return head',
  ],
  remove: [
    'procedure listRemove(head, pos)',
    '  if pos = 0 then',
    '    head ← head.next',
    '    remove old head',
    '  else',
    '    cur ← head',
    '    advance cur to position pos - 1',
    '    cur.next ← cur.next.next',
    '    remove node at pos',
    '    return head',
  ],
};

export const TREE_PSEUDOCODE = {
  insert: [
    'procedure treeInsert(node, value)',
    '  if node = null then return new Node(value)',
    '  if value < node.value then',
    '    node.left ← treeInsert(node.left, value)',
    '  else if value > node.value then',
    '    node.right ← treeInsert(node.right, value)',
    '  else return node  // duplicate',
    '  node.height ← 1 + max(left.height, right.height)',
    '  balance ← height(left) - height(right)',
    '  if balance > 1 and value < left.value then rotate right',
    '  if balance < -1 and value > right.value then rotate left',
    '  // double rotations rebalance at the child first',
    '  return node',
  ],
  delete: [
    'procedure treeDelete(node, value)',
    '  if node = null then return null  // missing',
    '  if value < node.value then node.left ← treeDelete(node.left, value)',
    '  else if value > node.value then node.right ← treeDelete(node.right, value)',
    '  // value found at this node',
    '  if node has two children then',
    '    successor ← min(node.right)',
    '    node.value ← successor.value',
    '    node.right ← treeDelete(node.right, successor.value)',
    '  else if node has one child then node ← only child',
    '  else node ← null',
    '  rebalance ancestors  // heights + rotations',
    '  return node',
  ],
  search: [
    'procedure treeSearch(node, value)',
    '  while node ≠ null do',
    '    if value = node.value then return node',
    '    if value < node.value then node ← node.left',
    '    else node ← node.right',
    '  return null',
  ],
  'traversal-preOrder': [
    'procedure preOrder(node)',
    '  if node = null then return',
    '  visit(node)',
    '  preOrder(node.left)',
    '  preOrder(node.right)',
    'end procedure',
  ],
  'traversal-inOrder': [
    'procedure inOrder(node)',
    '  if node = null then return',
    '  inOrder(node.left)',
    '  visit(node)',
    '  inOrder(node.right)',
    'end procedure',
  ],
  'traversal-postOrder': [
    'procedure postOrder(node)',
    '  if node = null then return',
    '  postOrder(node.left)',
    '  postOrder(node.right)',
    '  visit(node)',
    'end procedure',
  ],
  'traversal-levelOrder': [
    'procedure levelOrder(root)',
    '  queue ← [root]',
    '  while queue not empty do',
    '    node ← dequeue(queue)',
    '    visit(node)',
    '    if node.left ≠ null then enqueue(queue, node.left)',
    '    if node.right ≠ null then enqueue(queue, node.right)',
    'end procedure',
  ],
};

export const STACK_PSEUDOCODE = {
  push: [
    'procedure stackPush(stack, value)',
    '  n ← length(stack)',
    '  stack[n] ← value',
    '  size ← n + 1',
    'end procedure',
  ],
  pop: [
    'procedure stackPop(stack)',
    '  n ← length(stack)',
    '  removed ← stack[n - 1]',
    '  size ← n - 1',
    '  return removed',
    'end procedure',
  ],
  peek: [
    'procedure stackPeek(stack)',
    '  n ← length(stack)',
    '  top ← stack[n - 1]',
    '  return top',
    'end procedure',
  ],
};

export const QUEUE_PSEUDOCODE = {
  enqueue: [
    'procedure queueEnqueue(queue, value)',
    '  n ← length(queue)',
    '  queue[n] ← value',
    '  size ← n + 1',
    'end procedure',
  ],
  dequeue: [
    'procedure queueDequeue(queue)',
    '  n ← length(queue)',
    '  removed ← queue[0]',
    '  for i ← 1 to n - 1 do',
    '    queue[i - 1] ← queue[i]',
    '  size ← n - 1',
    '  return removed',
    'end procedure',
  ],
  peek: [
    'procedure queuePeek(queue)',
    '  front ← queue[0]',
    '  return front',
    'end procedure',
  ],
};

export const HASH_TABLE_PSEUDOCODE = {
  insert: [
    'procedure hashInsert(table, key)',
    '  h ← hash(key)',
    '  chain ← bucket[h]',
    '  if chain is empty then',
    '    bucket[h] ← [key]',
    '  else',
    '    append key to chain',
    '  size ← size + 1',
    'end procedure',
  ],
  search: [
    'procedure hashSearch(table, key)',
    '  h ← hash(key)',
    '  chain ← bucket[h]',
    '  if chain is empty then',
    '    return not found',
    '  for i ← 0 to length(chain) - 1 do',
    '    if chain[i] = key then',
    '      return i',
    '  return not found',
    'end procedure',
  ],
  delete: [
    'procedure hashDelete(table, key)',
    '  h ← hash(key)',
    '  chain ← bucket[h]',
    '  if chain is empty then',
    '    return not found',
    '  for i ← 0 to length(chain) - 1 do',
    '    if chain[i] = key then',
    '      for j ← i+1 to length(chain)-1 do',
    '        chain[j - 1] ← chain[j]',
    '      size ← size - 1',
    '      return i',
    '  return not found',
    'end procedure',
  ],
};

export const GRAPH_PSEUDOCODE = {
  addNode: [
    'procedure graphAddNode(graph, value)',
    '  graph.nodes ← graph.nodes ∪ {value}',
    '  n ← n + 1',
    'end procedure',
  ],
  addEdge: [
    'procedure graphAddEdge(graph, u, v)',
    '  assert u ∈ nodes ∧ v ∈ nodes',
    '  assert (u, v) ∉ edges ∧ u ≠ v',
    '  edges ← edges ∪ {(u, v)}',
    '  e ← e + 1',
    'end procedure',
  ],
  bfs: [
    'procedure graphBFS(graph, start)',
    '  queue ← [start]',
    '  visited ← ∅',
    '  while queue ≠ ∅ do',
    '    u ← dequeue(queue)',
    '    visit u',
    '    for each neighbor v of u do',
    '      if v ∉ visited then',
    '        visited ← visited ∪ {v}',
    '        enqueue(queue, v)',
    '  return visit order',
    'end procedure',
  ],
  dfs: [
    'procedure graphDFS(graph, start)',
    '  visited ← ∅',
    '  order ← []',
    '  procedure visit(u)',
    '    visited ← visited ∪ {u}',
    '    order ← order ∪ [u]',
    '    for each neighbor v of u do',
    '      if v ∈ visited then skip v',
    '      else visit(v)',
    '  visit(start)',
    '  return order',
    'end procedure',
  ],
};

export const LINKED_LIST_DOUBLY_PSEUDOCODE = {
  add: [
    'procedure listAddDoubly(head, value)',
    '  node ← newNode(value)',
    '  if head = null then',
    '    head ← node',
    '  else',
    '    cur ← head',
    '    while cur.next ≠ null do cur ← cur.next',
    '    node.prev ← cur',
    '    cur.next ← node',
    '  return head',
  ],
  insert: [
    'procedure listInsertDoubly(head, value, pos)',
    '  node ← newNode(value)',
    '  if pos = 0 then',
    '    node.next ← head',
    '    node.prev ← null',
    '    head ← node',
    '  else',
    '    cur ← head',
    '    advance cur to position pos - 1',
    '    node.prev ← cur',
    '    node.next ← cur.next',
    '    cur.next ← node',
    '    if node.next ≠ null then node.next.prev ← node',
    '  return head',
  ],
  remove: [
    'procedure listRemoveDoubly(head, pos)',
    '  if pos = 0 then',
    '    head ← head.next',
    '    if head ≠ null then head.prev ← null',
    '    remove old head',
    '  else',
    '    cur ← head',
    '    advance cur to position pos - 1',
    '    victim ← cur.next',
    '    cur.next ← victim.next',
    '    if victim.next ≠ null then victim.next.prev ← cur',
    '    remove victim',
    '  return head',
  ],
};

export const LINKED_LIST_CIRCULAR_PSEUDOCODE = {
  add: [
    'procedure listAddCircular(head, value)',
    '  node ← newNode(value)',
    '  if head = null then',
    '    head ← node',
    '    node.next ← node',
    '  else',
    '    cur ← head',
    '    while cur.next ≠ head do cur ← cur.next',
    '    node.next ← head',
    '    cur.next ← node',
    '  return head',
  ],
  insert: [
    'procedure listInsertCircular(head, value, pos)',
    '  node ← newNode(value)',
    '  if pos = 0 then',
    '    node.next ← head',
    '    tail ← head',
    '    while tail.next ≠ head do tail ← tail.next',
    '    tail.next ← node',
    '    head ← node',
    '  else',
    '    cur ← head',
    '    advance cur to position pos - 1',
    '    node.next ← cur.next',
    '    cur.next ← node',
    '  return head',
  ],
  remove: [
    'procedure listRemoveCircular(head, pos)',
    '  if head = null then return null',
    '  if pos = 0 then',
    '    tail ← head',
    '    while tail.next ≠ head do tail ← tail.next',
    '    head ← head.next',
    '    if head ≠ null then tail.next ← head',
    '    remove old head',
    '  else',
    '    cur ← head',
    '    advance cur to position pos - 1',
    '    cur.next ← cur.next.next',
    '    remove node at pos',
    '  return head',
  ],
};

export const DEQUE_PSEUDOCODE = {
  pushFront: [
    'procedure dequePushFront(deque, value)',
    '  n ← length(deque)',
    '  for i ← n - 1 downto 0 do',
    '    deque[i + 1] ← deque[i]',
    '  deque[0] ← value',
    '  n ← n + 1',
    'end procedure',
  ],
  pushRear: [
    'procedure dequePushRear(deque, value)',
    '  n ← length(deque)',
    '  deque[n] ← value',
    '  n ← n + 1',
    'end procedure',
  ],
  popFront: [
    'procedure dequePopFront(deque)',
    '  n ← length(deque)',
    '  removed ← deque[0]',
    '  for i ← 1 to n - 1 do',
    '    deque[i - 1] ← deque[i]',
    '  n ← n - 1',
    '  return removed',
    'end procedure',
  ],
  popRear: [
    'procedure dequePopRear(deque)',
    '  n ← length(deque)',
    '  removed ← deque[n - 1]',
    '  n ← n - 1',
    '  return removed',
    'end procedure',
  ],
};

export const CIRCULAR_QUEUE_PSEUDOCODE = {
  enqueue: [
    'procedure circularEnqueue(ring, value)',
    '  if count = capacity then error "full"',
    '  rear ← (front + count) mod capacity',
    '  ring[rear] ← value',
    '  count ← count + 1',
    'end procedure',
  ],
  dequeue: [
    'procedure circularDequeue(ring)',
    '  if count = 0 then error "empty"',
    '  removed ← ring[front]',
    '  front ← (front + 1) mod capacity',
    '  count ← count - 1',
    '  return removed',
    'end procedure',
  ],
  peek: [
    'procedure circularPeek(ring)',
    '  if count = 0 then error "empty"',
    '  return ring[front]',
    'end procedure',
  ],
};
