// Pseudocode listings for the dual-pane player. Line numbers referenced by
// step builders (`step.line`) are 1-based indexes into these arrays.

export const ARRAY_PSEUDOCODE = {
  add: [
    'procedure arrayAdd(array, value)',
    '  n ← length(array)',
    '  array[n] ← value',
    '  length ← n + 1',
    'end procedure',
  ],
  insert: [
    'procedure arrayInsert(array, pos, value)',
    '  n ← length(array)',
    '  for i ← n downto pos + 1 do',
    '    array[i] ← array[i - 1]',
    '  array[pos] ← value',
    '  length ← n + 1',
    'end procedure',
  ],
  remove: [
    'procedure arrayRemove(array, pos)',
    '  locate index pos',
    '  removed ← array[pos]',
    '  for i ← pos to length(array) - 2 do',
    '    array[i] ← array[i + 1]',
    '  length ← length(array) - 1',
    '  return removed',
    'end procedure',
  ],
};

export const LINKED_LIST_PSEUDOCODE = {
  add: [
    'procedure listAdd(head, value)',
    '  node ← newNode(value)',
    '  if head = null then',
    '    head ← node',
    '  else',
    '    cur ← head',
    '    while cur.next ≠ null do cur ← cur.next',
    '    cur.next ← node',
    '  return head',
  ],
  insert: [
    'procedure listInsert(head, value, pos)',
    '  node ← newNode(value)',
    '  if pos = 0 then',
    '    node.next ← head',
    '    head ← node',
    '  else',
    '    cur ← head',
    '    advance cur to position pos - 1',
    '    node.next ← cur.next',
    '    cur.next ← node',
    '  return head',
  ],
  remove: [
    'procedure listRemove(head, pos)',
    '  if pos = 0 then',
    '    head ← head.next',
    '    remove old head',
    '  else',
    '    cur ← head',
    '    advance cur to position pos - 1',
    '    cur.next ← cur.next.next',
    '    remove node at pos',
    '    return head',
  ],
};

export const TREE_PSEUDOCODE = {
  insert: [
    'procedure treeInsert(node, value)',
    '  if node = null then return new Node(value)',
    '  if value < node.value then',
    '    node.left ← treeInsert(node.left, value)',
    '  else if value > node.value then',
    '    node.right ← treeInsert(node.right, value)',
    '  else return node  // duplicate',
    '  node.height ← 1 + max(left.height, right.height)',
    '  balance ← height(left) - height(right)',
    '  if balance > 1 and value < left.value then rotate right',
    '  if balance < -1 and value > right.value then rotate left',
    '  // double rotations rebalance at the child first',
    '  return node',
  ],
  delete: [
    'procedure treeDelete(node, value)',
    '  if node = null then return null  // missing',
    '  if value < node.value then node.left ← treeDelete(node.left, value)',
    '  else if value > node.value then node.right ← treeDelete(node.right, value)',
    '  // value found at this node',
    '  if node has two children then',
    '    successor ← min(node.right)',
    '    node.value ← successor.value',
    '    node.right ← treeDelete(node.right, successor.value)',
    '  else if node has one child then node ← only child',
    '  else node ← null',
    '  rebalance ancestors  // heights + rotations',
    '  return node',
  ],
  search: [
    'procedure treeSearch(node, value)',
    '  while node ≠ null do',
    '    if value = node.value then return node',
    '    if value < node.value then node ← node.left',
    '    else node ← node.right',
    '  return null',
  ],
  'traversal-preOrder': [
    'procedure preOrder(node)',
    '  if node = null then return',
    '  visit(node)',
    '  preOrder(node.left)',
    '  preOrder(node.right)',
    'end procedure',
  ],
  'traversal-inOrder': [
    'procedure inOrder(node)',
    '  if node = null then return',
    '  inOrder(node.left)',
    '  visit(node)',
    '  inOrder(node.right)',
    'end procedure',
  ],
  'traversal-postOrder': [
    'procedure postOrder(node)',
    '  if node = null then return',
    '  postOrder(node.left)',
    '  postOrder(node.right)',
    '  visit(node)',
    'end procedure',
  ],
  'traversal-levelOrder': [
    'procedure levelOrder(root)',
    '  queue ← [root]',
    '  while queue not empty do',
    '    node ← dequeue(queue)',
    '    visit(node)',
    '    if node.left ≠ null then enqueue(queue, node.left)',
    '    if node.right ≠ null then enqueue(queue, node.right)',
    'end procedure',
  ],
};
